#!/usr/bin/env bash
set -eux -o pipefail

if ! command -v ipfs > /dev/null; then
    brew install ipfs
fi

if [[ ! -f "${HOME}/.ipfs/swarm.key" ]]; then
    IPFS_SWARM_KEY=$(openssl rand -hex 32)
    SWARM_KEY_PATH="${HOME}/.ipfs/swarm.key"
    mkdir -p "${HOME}/.ipfs"
    echo "/key/swarm/psk/1.0.0/" > "${SWARM_KEY_PATH}"
    echo "/base16/" >> "${SWARM_KEY_PATH}"
    echo "${IPFS_SWARM_KEY}" >> "${SWARM_KEY_PATH}"
fi

ipfs init
ipfs daemon
ipfs bootstrap rm --all
ipfs id
